### ISSUE TITLE
Fix rsslay missing post

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/rsslay#17]
Clients are not showing the latest Yaka Stuff blog post from the rss.nos.social relay. Presumably this is an issue with rsslay. Let's figure out why this is happening and fix it. Tested in Nos and Damus.

![Image](https://github.com/planetary-social/nos/assets/1165004/64e798c7-dd1f-45d7-b948-245b3381afe5)

**Comment by boreq** [comment]
Maybe #16

**Comment by mplorentz** [comment]
Closing this and we can reopen if we see it again.
